pipeline {
  agent any

  options {
    buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    disableConcurrentBuilds()
  }

  parameters {
    booleanParam(name: 'isGoingToDeploy', defaultValue: false)
  }

  stages {
    stage('Testing CI for dev branch') {
      steps {
        echo 'Hello world'
      }
    }

    stage('Enable CD') {
      steps {
        build job: 'proesc-backend/cd-dev',
          wait: false,
          propagate: false
      }

      when {
        expression {
          return params.isGoingToDeploy
        }
      }
    }
  }
}